services:
  juice-shop:
    image: bkimminich/juice-shop:v17.2.0
    container_name: juice-shop
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      NODE_ENV: unsafe
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
